spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  resources:
    static-locations:
      - file:///${jk.upload.base-path}

mybatis-plus:
  type-aliases-package: com.haitunhv.jk.pojo
  configuration:
    use-generated-keys: true
  global-config:
    db-config:
      id-type: auto

