spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/xr?serverTimezone=UTC
    druid:
      initial-size: 5
      max-active: 10

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.mj.domain
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true